# Generated by Django 5.2.12 on 2026-03-18 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        ('features', '0002_features_flow_type_features_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credittransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='featurecreditrule',
            name='credits_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='featurecreditrule',
            name='feature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_rule', to='features.features'),
        ),
        migrations.AlterField(
            model_name='usercredits',
            name='id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercredits',
            name='total_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercredits',
            name='used_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
