# Generated by Django 5.2.12 on 2026-03-18 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_credittransaction_balance_after_and_more'),
        ('templates', '0008_alter_aimodel_credit_cost_alter_template_credit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.template'),
        ),
        migrations.DeleteModel(
            name='FeatureCreditRule',
        ),
    ]
