# Generated by Django 5.2.12 on 2026-03-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_credittransaction_template_delete_featurecreditrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='balance_before',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercredits',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
