# Generated by Django 5.2.12 on 2026-04-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_rename_description_credittransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('add', 'Add'), ('deduct', 'Deduct')], default='credit', max_length=10),
            preserve_default=False,
        ),
    ]
