# Generated by Django 5.2.12 on 2026-04-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0007_credittransaction_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credittransaction',
            old_name='transaction_type',
            new_name='transaction_action',
        ),
    ]
