# Generated by Django 5.2.12 on 2026-04-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0008_rename_transaction_type_credittransaction_transaction_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credittransaction',
            old_name='description',
            new_name='transaction_type',
        ),
    ]
