# Generated by Django 5.2.12 on 2026-03-17 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0006_rename_model_key_aimodel_model_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default='default_job', editable=False, max_length=20, unique=True)),
                ('input_data', models.JSONField()),
                ('result_url', models.URLField(blank=True, max_length=500, null=True)),
                ('result_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=20, null=True)),
                ('output_metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('credit_used', models.IntegerField(default=1)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='templates.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='generations_user_id_b5ad8c_idx'), models.Index(fields=['status'], name='generations_status_ae0db1_idx'), models.Index(fields=['job_id'], name='generations_job_id_f4c1d0_idx')],
            },
        ),
    ]
