# Generated by Django 5.2.12 on 2026-03-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='job_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
