# Generated by Django 5.2.12 on 2026-03-18 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('generations', '0002_alter_generation_job_id'),
        ('templates', '0006_rename_model_key_aimodel_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='features.features'),
        ),
        migrations.AddField(
            model_name='generation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('template', 'Template'), ('feature', 'Feature')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='templates.template'),
        ),
    ]
