# Generated by Django 5.2.12 on 2026-03-19 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_features_credit_cost'),
        ('generations', '0003_generation_feature_generation_source_type_and_more'),
        ('templates', '0008_alter_aimodel_credit_cost_alter_template_credit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='input_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='generation',
            name='model_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='request_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='response_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['user', 'created_at'], name='generations_user_id_568964_idx'),
        ),
    ]
