# Generated by Django 5.2.12 on 2026-03-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0004_generation_input_summary_generation_max_retries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='is_credits_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generation',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generation',
            name='credit_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True),
        ),
    ]
