# Generated by Django 5.2.12 on 2026-04-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0005_generation_is_credits_deducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='used_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
