# Generated by Django 5.2.12 on 2026-04-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0006_generation_used_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('template', 'Template'), ('feature', 'Feature'), ('auto_video', 'Auto Video')], max_length=20, null=True),
        ),
    ]
