# Generated by Django 5.2.12 on 2026-04-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='display_type',
            field=models.CharField(choices=[('notification', 'Notification'), ('slider', 'Slider'), ('both', 'Both')], default='notification', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='media',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True),
        ),
    ]
