# Generated by Django 5.2.12 on 2026-04-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_display_type_notification_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
