# Generated by Django 5.2.12 on 2026-04-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='cta_text',
        ),
    ]
