# Generated by Django 5.2.12 on 2026-04-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_cta_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_dismissible',
        ),
    ]
