# Generated by Django 5.2.12 on 2026-04-18 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_notification_banner_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='delay_max',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='delay_min',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='last_sent_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='time_of_day',
        ),
        migrations.AddField(
            model_name='notification',
            name='trigger_type',
            field=models.CharField(choices=[('instant', 'Instant'), ('delay', 'Delay after open'), ('after_actions', 'After actions'), ('first_video', 'After first video'), ('idle', 'User idle')], default='instant', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='trigger_value',
            field=models.IntegerField(blank=True, help_text='Seconds / action count depending on trigger', null=True),
        ),
        migrations.CreateModel(
            name='NotificationSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NotificationTrigger',
        ),
    ]
