# Generated by Django 5.2.12 on 2026-03-18 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0006_rename_model_key_aimodel_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('credit_cost', models.IntegerField()),
                ('feature_type', models.CharField(choices=[('text_to_video', 'Text to Video'), ('image_to_video', 'Image to Video'), ('couple_wallpaper', 'Couple Wallpaper'), ('background_remove', 'Background Remove'), ('background_change', 'Background Change'), ('image_upscale', 'Image Upscale'), ('image_colorize', 'Image Colorize')], max_length=50)),
                ('input_schema', models.JSONField()),
                ('default_settings', models.JSONField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_models', models.ManyToManyField(related_name='features', to='templates.aimodel')),
                ('default_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_features', to='templates.aimodel')),
            ],
        ),
    ]
