# Generated by Django 5.2.12 on 2026-03-18 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('templates', '0006_rename_model_key_aimodel_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='flow_type',
            field=models.CharField(choices=[('ai', 'AI Generation'), ('template', 'Template Flow')], default='ai', max_length=20),
        ),
        migrations.AddField(
            model_name='features',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='templates.template'),
        ),
    ]
