# Generated by Django 5.2.12 on 2026-03-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_features_flow_type_features_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='credit_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
