# Generated by Django 5.2.12 on 2026-03-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_features_credit_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='flow_type',
        ),
        migrations.AlterField(
            model_name='features',
            name='feature_type',
            field=models.CharField(choices=[('text_to_video', 'Text to Video'), ('image_to_video', 'Image to Video'), ('background_remove', 'Background Remove'), ('background_change', 'Background Change'), ('image_upscale', 'Image Upscale'), ('image_colorize', 'Image Colorize')], max_length=50),
        ),
    ]
