# Generated by Django 5.2.12 on 2026-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_remove_features_flow_type_and_more'),
        ('templates', '0008_alter_aimodel_credit_cost_alter_template_credit_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='template',
        ),
        migrations.AlterField(
            model_name='features',
            name='allowed_models',
            field=models.ManyToManyField(blank=True, related_name='features', to='templates.aimodel'),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature_type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='input_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
