# Generated by Django 5.2.12 on 2026-03-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_remove_features_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='model_mapping',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
