# Generated by Django 5.2.12 on 2026-03-20 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_features_model_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='credit_cost',
        ),
        migrations.RemoveField(
            model_name='features',
            name='default_settings',
        ),
        migrations.AddField(
            model_name='features',
            name='advanced_credit_cost',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='features',
            name='fast_credit_cost',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='features',
            name='standard_credit_cost',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='FeatureSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('fast', 'Fast'), ('standard', 'Standard'), ('advanced', 'Advanced')], max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('type', models.CharField(default='select', max_length=50)),
                ('options', models.JSONField(default=list)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='features.features')),
            ],
            options={
                'unique_together': {('feature', 'mode', 'key')},
            },
        ),
    ]
