# Generated by Django 5.2.12 on 2026-03-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_remove_features_credit_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuresetting',
            options={'ordering': ('mode', 'display_order')},
        ),
        migrations.AddField(
            model_name='features',
            name='is_multi_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featuresetting',
            name='default_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
