# Generated by Django 5.2.12 on 2026-03-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_alter_featuresetting_options_features_is_multi_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='credit_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='advanced_credit_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='fast_credit_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='standard_credit_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
