# Generated by Django 5.2.12 on 2026-03-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_features_credit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='credits_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
