# Generated by Django 5.2.12 on 2026-03-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_features_credits_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='features',
            name='input_schema',
        ),
    ]
