# Generated by Django 5.2.12 on 2026-03-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_remove_features_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='features',
            name='input_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
