# Generated by Django 5.2.12 on 2026-04-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_features_display_order_features_input_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuresetting',
            options={'ordering': ('input_type', 'mode', 'display_order')},
        ),
        migrations.AlterUniqueTogether(
            name='featuresetting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='featuresetting',
            name='input_type',
            field=models.CharField(blank=True, choices=[('one_image', 'One Image'), ('two_image', 'Two Image')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='featuresetting',
            unique_together={('feature', 'input_type', 'mode', 'key')},
        ),
    ]
