# Generated by Django 5.2.12 on 2026-04-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_alter_featuresetting_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='advanced_credit_cost',
        ),
        migrations.RemoveField(
            model_name='features',
            name='fast_credit_cost',
        ),
        migrations.RemoveField(
            model_name='features',
            name='standard_credit_cost',
        ),
    ]
