# Generated by Django 5.2.12 on 2026-03-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('model_key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('feature_type', models.CharField(choices=[('text_to_video', 'Text to Video'), ('image_to_video', 'Image to Video'), ('background_remove', 'Background Remove'), ('background_change', 'Background Change'), ('image_upscale', 'Image Upscale'), ('image_colorize', 'Image Colorize')], max_length=50)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_cost', models.IntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cover_image', models.URLField()),
                ('credit_cost', models.IntegerField()),
                ('feature_type', models.CharField(choices=[('text_to_video', 'Text to Video'), ('image_to_video', 'Image to Video'), ('background_remove', 'Background Remove'), ('background_change', 'Background Change'), ('image_upscale', 'Image Upscale'), ('image_colorize', 'Image Colorize')], max_length=50)),
                ('prompt_template', models.TextField(blank=True, null=True)),
                ('input_schema', models.JSONField()),
                ('default_settings', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_models', models.ManyToManyField(related_name='templates', to='templates.aimodel')),
            ],
        ),
    ]
