# Generated by Django 5.2.12 on 2026-03-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('popular', 'Popular'), ('family', 'Family'), ('trending', 'Trending'), ('love', 'Love'), ('birthday', 'Birthday'), ('photoshoot', 'Photoshoot'), ('new', 'New'), ('kids', 'Kids'), ('wedding', 'Wedding'), ('dance', 'Dance'), ('B&W', 'B&W')], default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
