# Generated by Django 5.2.12 on 2026-03-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_template_category_template_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='preview_media',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='template',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
