# Generated by Django 5.2.12 on 2026-03-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_template_preview_media_alter_template_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='cover_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
