# Generated by Django 5.2.12 on 2026-03-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_alter_template_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='feature_type',
            field=models.CharField(choices=[('text_to_video', 'Text to Video'), ('image_to_video', 'Image to Video'), ('image_to_image', 'Image to Image'), ('background_remove', 'Background Remove'), ('background_change', 'Background Change'), ('image_upscale', 'Image Upscale'), ('image_colorize', 'Image Colorize')], max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='feature_type',
            field=models.CharField(choices=[('text_to_video', 'Text to Video'), ('image_to_video', 'Image to Video'), ('image_to_image', 'Image to Image'), ('background_remove', 'Background Remove'), ('background_change', 'Background Change'), ('image_upscale', 'Image Upscale'), ('image_colorize', 'Image Colorize')], max_length=50),
        ),
    ]
