# Generated by Django 5.2.12 on 2026-03-17 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_alter_aimodel_feature_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='model_key',
            new_name='model_name',
        ),
        migrations.AddField(
            model_name='template',
            name='default_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_templates', to='templates.aimodel'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='feature_type',
            field=models.CharField(choices=[('text_to_video', 'Text to Video'), ('image_to_video', 'Image to Video'), ('image_generation', 'Image Generation'), ('image_edit', 'Image Edit'), ('background_remove', 'Background Remove'), ('background_change', 'Background Change'), ('image_upscale', 'Image Upscale'), ('image_colorize', 'Image Colorize')], max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('popular', 'Popular'), ('family', 'Family'), ('trending', 'Trending'), ('love', 'Love'), ('birthday', 'Birthday'), ('photoshoot', 'Photoshoot'), ('new', 'New'), ('kids', 'Kids'), ('wedding', 'Wedding'), ('dance', 'Dance'), ('bw', 'B&W')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='feature_type',
            field=models.CharField(choices=[('text_to_video', 'Text to Video'), ('image_to_video', 'Image to Video'), ('image_generation', 'Image Generation'), ('image_edit', 'Image Edit'), ('background_remove', 'Background Remove'), ('background_change', 'Background Change'), ('image_upscale', 'Image Upscale'), ('image_colorize', 'Image Colorize')], max_length=50),
        ),
    ]
