# Generated by Django 5.2.12 on 2026-03-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_alter_aimodel_feature_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='credit_cost',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='template',
            name='credit_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
