# Generated by Django 5.2.12 on 2026-03-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0008_alter_aimodel_credit_cost_alter_template_credit_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='feature_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['feature_type'], name='templates_a_feature_6245e3_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['model_name'], name='templates_a_model_n_98e2ee_idx'),
        ),
    ]
