# Generated by Django 5.2.12 on 2026-03-20 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_remove_features_template_and_more'),
        ('templates', '0009_remove_aimodel_is_default_alter_aimodel_feature_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='features.features'),
        ),
    ]
