# Generated by Django 5.2.12 on 2026-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_features_credits_config'),
        ('templates', '0010_aimodel_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='total_credits_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='total_usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['is_active'], name='templates_a_is_acti_efd459_idx'),
        ),
    ]
