# Generated by Django 5.2.12 on 2026-03-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0011_aimodel_total_credits_used_aimodel_total_usage_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationConfig',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('config_type', models.CharField(choices=[('auto_video', 'Auto Video')], max_length=50)),
                ('feature_type', models.CharField(choices=[('text_to_video', 'Text to Video'), ('image_to_video', 'Image to Video'), ('image_edit', 'Image Edit'), ('couple_wallpaper', 'Couple Wallpaper'), ('background_remove', 'Background Remove'), ('background_change', 'Background Change'), ('image_upscale', 'Image Upscale'), ('image_colorize', 'Image Colorize')], max_length=50)),
                ('prompt_template', models.TextField()),
                ('default_settings', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.aimodel')),
            ],
        ),
    ]
