# Generated by Django 5.2.12 on 2026-03-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0012_generationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationconfig',
            name='credits',
            field=models.PositiveIntegerField(default=1, help_text='Credits required to run this generation config'),
        ),
    ]
