# Generated by Django 5.2.12 on 2026-04-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0013_generationconfig_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
