# Generated by Django 5.2.12 on 2026-04-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0014_template_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generationconfig',
            old_name='credits',
            new_name='credit_cost',
        ),
    ]
