# Generated by Django 5.2.12 on 2026-04-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0015_rename_credits_generationconfig_credit_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationconfig',
            name='prompt_template',
        ),
        migrations.AddField(
            model_name='generationconfig',
            name='prompt_templates',
            field=models.JSONField(default=list, help_text='List of prompts. System will randomly pick one.'),
        ),
    ]
