# Generated by Django 5.2.12 on 2026-04-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0016_remove_generationconfig_prompt_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generationconfig',
            old_name='prompt_templates',
            new_name='prompt_template',
        ),
    ]
