# Generated by Django 5.2.12 on 2026-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_slider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planslide',
            name='title',
        ),
        migrations.AlterField(
            model_name='planslide',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
