# Generated by Django 5.2.12 on 2026-03-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_usersubscription_current_plan_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='price',
            new_name='price_inr',
        ),
    ]
