# Generated by Django 5.2.12 on 2026-03-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_rename_price_plan_price_inr'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
