# Generated by Django 5.2.12 on 2026-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='media',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
