# Generated by Django 5.2.12 on 2026-04-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_plan_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='media',
        ),
    ]
