# Generated by Django 5.2.12 on 2026-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_google_id_user_login_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('banned', 'Banned')], default='new', max_length=10),
        ),
    ]
